inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'sushi_counter_app.git/**/*'

require:
  - rubocop-rails

